import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Important for correct mobile rendering
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata = {
  title: "Match Planning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          "min-h-dvh bg-gray-50 text-gray-900 antialiased",
        ].join(" ")}
      >
        {children}
      </body>
    </html>
  );
}
